name: Build Resume and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy in TeXLive environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            # Install required LaTeX packages
            tlmgr update --self
            tlmgr install ltxcmds pdfescape kvoptions hyperref

            # Set up Python environment
            apk add --no-cache python3 py3-pip
            python3 -m venv /tmp/venv
            . /tmp/venv/bin/activate
            pip install pyyaml jinja2

            # Build the resume
            python render_resume.py

            # Deploy to gh-pages
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            if git show-ref --quiet refs/heads/gh-pages; then
              git checkout gh-pages
            else
              git checkout --orphan gh-pages
            fi
            git rm -rf .
            git add hagimoto-resume.pdf
            git commit -m "Deploy hagimoto-resume.pdf"
            git push origin gh-pages --force
