name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Clean up old output
        run: rm -rf output && mkdir -p output

      - name: Build Docker image
        run: docker build -t resume-builder .

      - name: Run resume build in Docker
        run: |
          docker run --name resume-container \
            -e OUTPUT_DIR=output \
            -v ${{ github.workspace }}/output:/app/output \
            resume-builder python3 compile_resume.py
          docker rm -f resume-container || true

      - name: List outputs
        run: ls -l output

      - name: Upload resume PDF(s)
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdfs
          path: output/*.pdf

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Switch to or create gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          git rm -rf .
          cp output/*.pdf ./
          git add *.pdf
          git commit -m "Deploy resume PDF(s)"
          git push origin gh-pages --force