name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml jinja2

      - name: Compile template
        run: python compile_template.py

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src
          pre_compile: |
            tlmgr update --self
            tlmgr install ltxcmds pdfescape kvoptions hyperref

      - name: Move PDF to root
        run: mv src/main.pdf hagimoto-resume.pdf

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi
          git rm -rf .
          git add hagimoto-resume.pdf
          git commit -m "Deploy hagimoto-resume.pdf"
          git push origin gh-pages --force
