name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t resume-builder .

      - name: Build resume
        run: docker run --rm -v "$(pwd):/resume" resume-builder bash -c "chmod +x build.sh && ./build.sh"

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi
          git rm -rf .
          git add hagimoto-resume.pdf
          git commit -m "Deploy hagimoto-resume.pdf"
          git push origin gh-pages --force
