name: Build Resume

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t resume-builder .

      - name: Build resume
        run: docker run --rm -v "$(pwd):/resume" resume-builder bash -c "chmod +x build.sh && ./build.sh"

      - name: Deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Switch to or create gh-pages
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi
          
          # Clean working tree
          git rm -rf .

          # Copy PDFs from output/
          cp output/*.pdf ./
          
          # Stage and commit
          git add *.pdf
          git commit -m "Deploy resume PDF(s)"
          git push origin gh-pages --force
